matrix:
  include:

    # mac_cmake
    - os: osx
      env: BUILD_TARGET=mac_cmake
      language: cpp
      sudo: required
      osx_image: xcode11.3
    - os: windows
      env: CMAKE_PATH="/c/Program Files/CMake/bin"
      language: cpp
#    - os: linux
#      dist: xenial
#      env: 
#        - BUILD_TARGET=linux 
#        - GEN_BINDING_AND_COCOSFILE=true
#        - secure: Xn48eX1TD6DAPcVPU+a+CD3b/BKGVCHk555zl8rZiLq4GH4rWSES23rKcY8uz/X9GizETWYQK2luNvph4/BA29XEZ7l+Q0V9AZwrahWPzCuDBgxSPAr4KlETGM9I3xEvRIKBeddko7JTFHZCcNsItPRA0CovndQzdKE6texm13A=
#        - secure: M31OQaUIBV13aUMylPs2PieKThGs+ED0tj9SKbCKGKxwojl+N2ZhlS53D4Zqoj1ru/3P1X0pPeYvV0uVfM2dpEwRF4BmYVZQSrOKgjK1VfbcN5luWSeuAvq0LNGT99Ao02sKLbcHINiQ4axylPPgsY6+X/aoJNuKqBTQyaaVAo8=
#        - secure: M5lyDs0qai15mWHzJdkh0WPfVJJmVZu6SWtYULxatukGPXVwoQvmEtYAwAW+iz6aM+tXksQ/mk6nW5L8UFbHm+n6yrsa5bZU9sGXjilPE8p8bLFYDmIbPRazU+E6pBP3J2CDoAm0XnWkiYQ8feTxKTo6ysLnHAEjyaHTw0+Q1GM=
#      sudo: required
#      language: cpp
git:
  submodules: false
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then export BITBUCKET_USER_NAME=Bilalmirza  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then export BITBUCKET_USER_PASSWORD=wfYk9Q4wjvf9cdyd8tpj  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux"  ]]; then echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" >~/.netrc  ; fi 
  - git submodule update --init --recursive
script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=$CMAKE_PATH:$PATH  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export HOME=$(pwd); fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "$HOME"; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo machine bitbucket.org> _netrc  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo login Bilalmirza>> _netrc  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo password wfYk9Q4wjvf9cdyd8tpj>> _netrc  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cat _netrc; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
     echo -e "y" | bash /home/travis/build/Bilalmirza/Test/install-deps-linux.sh;
     sudo apt-get update;
     sudo apt-get install ninja-build;
     sudo apt-get install doxygen;
     ninja --version
    ;fi
  - git submodule add --depth 1 -- https://bitbucket.org/weRplay/explottens
  - cd explottens/Explottens
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake --build .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd bin/Debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r explottens Explottens; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project /Users/travis/build/Bilalmirza/Test/explottens/explottens/proj.ios_mac/Explottens.xcodeproj -configuration Release -scheme "explottens-desktop" CONFIGURATION_BUILD_DIR="/Users/travis/build/Bilalmirza/Test/bin" | xcpretty ;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake .. -DCMAKE_BUILD_TYPE=Release -T v140; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake --build . --config Release; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd bin; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd Explottens; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('Release', 'explottens.zip'); }"; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd /Users/travis/build/Bilalmirza/Test/bin;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r Explottens.zip Explottens.app;fi
  - export OUTPUTDIR=$PWD
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOCKEY_APP_ID=36131caa01d742e4bcf77917004df486;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export HOCKEY_APP_ID=bfedf0d2e3ff4048beb5ad6ad5e2ad55;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export HOCKEY_APP_ID=b66407ecde2d463a8fea94eed1c15159;fi

  - export HOCKEY_APP_TOKEN=e7bdafb86203468e98d28fbeb05ef943
  - printenv
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -X PUT -F "status=2" -F "notify=1" -F "notes=Some new features and fixed bugs." -F "notes_type=0" -F "ipa=@explottens.zip" -H "X-HockeyAppToken:$HOCKEY_APP_TOKEN" https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions/1;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -F "status=2" -F "notify=1" -F "notes=Some new features and fixed bugs." -F "notes_type=0" -F "ipa=@explottens.zip" -H "X-HockeyAppToken:$HOCKEY_APP_TOKEN" https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions/upload;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -X PUT -F "status=2" -F "notify=1" -F "notes=Some new features and fixed bugs." -F "notes_type=0" -F "ipa=@explottens.zip" -H "X-HockeyAppToken:$HOCKEY_APP_TOKEN" https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions/2;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git clone https://github.com/andreafabrizi/Dropbox-Uploader.git;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "OAUTH_ACCESS_TOKEN=vp0TyqCJLF0AAAAAAAACLF4EpS8qwQa23nhKzYqhdow0ekBQ4j67HfdRHjDsf8ox" > .dropbox_uploader;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./Dropbox-Uploader/dropbox_uploader.sh -f .dropbox_uploader explottens.zip explottens-win.zip;fi




