matrix:
  include:

    # mac_cmake
    - os: osx
     env: BUILD_TARGET=mac_cmake
     language: cpp
     osx_image: Xcode
     sudo: required
    # - os: windows
    #   language: cpp
    #   env:
    #     - CMAKE_PATH="/c/Program Files/CMake/bin"      
    #   script: 
    #     - export PATH=$CMAKE_PATH:$PATH
    #     - mkdir build && cd build
    #     - cmake .. 
    #     - cmake --build . 
git:
 submodules: false

before_install:
  - /Users/travis/build/Bilalmirza/Test/install.sh

#before_install:
  #- git clone http://github.com/cocos2d/cocos2d-x.git
  #- cd ./cocos2d-x
  #- python download-deps.py -r yes
  #- git submodule update --init
  #- export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
  #- export PATH=$PATH:$COCOS_CONSOLE_ROOT
  #- export COCOS_TEMPLATES_ROOT=`pwd`/templates
  #- export PATH=$PATH:$COCOS_TEMPLATES_ROOT
  #- cd ..
  #- echo `pwd`
  #- printenv
  #- xcodebuild -project /Users/travis/build/Bilalmirza/Test/proj.ios_mac/travis-test.xcodeproj -configuration Release -target "travis-test-desktop" CONFIGURATION_BUILD_DIR="/Users/travis/build/Bilalmirza/Test/output" | xcpretty

#install:
#- sudo -E sh ./install.sh

#script:
  #- cocos --agreement y
  #- cocos compile -p mac -m release -o output
  #- cd output
  #- zip -r travis.zip travis-test-desktop.app
  #- export OUTPUTDIR=$PWD
  #- export HOCKEY_APP_ID=36131caa01d742e4bcf77917004df486
  #- export HOCKEY_APP_TOKEN=598504c3bbb54916a6bb4e62c34ce683
  #- printenv
  #- curl -F "status=2" -F "notify=1" -F "notes=Some new features and fixed bugs." -F "notes_type=0" -F "ipa=@travis.zip" -H "X-HockeyAppToken:$HOCKEY_APP_TOKEN" https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions/upload


