matrix:
  include:

    # mac_cmake
    - os: osx
      env: BUILD_TARGET=mac_cmake
      language: cpp
      osx_image: Xcode
      sudo: required
git:
  submodules: false

before_install:
  - git clone http://github.com/cocos2d/cocos2d-x.git
  - cd ./cocos2d-x
  - python download-deps.py -r yes
  - git submodule update --init
  - export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
  - export PATH=$PATH:$COCOS_CONSOLE_ROOT
  - export COCOS_TEMPLATES_ROOT=`pwd`/templates
  - export PATH=$PATH:$COCOS_TEMPLATES_ROOT
  - cd ..
  - echo `pwd`
  - printenv
script:
  - cocos --agreement y
  - cocos compile -p mac -m release -o output
after_success:
  -OUTPUTDIR="$PWD/output/"
  -RELEASE_DATE=`date '+%Y-%m-%d %H:%M:%S'`
  -RELEASE_NOTES="Build: $TRAVIS_BUILD_NUMBER Uploaded: $RELEASE_DATE"
  -HOCKEY_APP_ID=36131caa01d742e4bcf77917004df486
  -HOCKEY_APP_TOKEN=2ccf0f45dd21ca95365f8e065ba06e16
  -curl https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions \
  -F status="2" 
  -F notify="0" 
  -F notes="$RELEASE_NOTES"
  -F notes_type="0" 
  -F tags="production" 
  -F ipa="@$OUTPUTDIR/$APP_NAME.app" 
  -F dsym="@$OUTPUTDIR/$APP_NAME.app.dSYM.zip" 
  -H "X-HockeyAppToken: $HOCKEY_APP_TOKEN"
  
