matrix:
  include:

    # mac_cmake
    - os: osx
      env: BUILD_TARGET=mac_cmake
      language: cpp
      osx_image: Xcode
      sudo: required
git:
  submodules: false

before_install:
  - git clone http://github.com/cocos2d/cocos2d-x.git
  - cd ./cocos2d-x
  - python download-deps.py -r yes
  - git submodule update --init
  - setup.py
  - echo ''
  - echo ''
  - echo ''
  - cd ..
  - echo `pwd`
  - printenv
  - cocos -v
script:
  - cocos compile -p mac -m release
  
